import React from "react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Services from '../components/services'
import About from '../components/aboutCard'
import NavMenu from '../components/navMenu';
import Contact from '../components/contactCard'
import VideoDisplay from '../components/videoDisplay';
import Footer from '../components/footer';
import HeaderCarousel from '../components/carousel';
import { GraphQLClient } from 'graphql-request';
import Script from 'next/script'



export default function Home({photographyServices, profile, carouselPhotos}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{profile.businessName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src={`https://maps.googleapis.com/maps/api/js?key=${process.env.API_KEY}`} />
      </Head>
      <NavMenu />
      <h1 className={styles.TitleAlign}>{profile.businessName}</h1>
      <HeaderCarousel carouselPhotos={carouselPhotos}/>
      <Services photographyServices={photographyServices}/>
      <About profile={profile}/>
      <VideoDisplay/>
      <Contact profile={profile}/>
      <Footer profile={profile}/>
    </div>
  )
}




const hygraph = new GraphQLClient(
    process.env.NEXT_PUBLIC_CLIENT_URL,
    {
      headers: {
        Authorization: `Bearer ${process.env.BEARER_TOKEN}`
      }
    }
  );

  import { gql } from 'graphql-request';



  const QUERY = gql`

    query Services {
      photographyServices {
        id
        serviceTitle
        photoSamples {
          id
          url
          width
          height
        }
      }
      profile(where: {businessName: "Go 2 You Portraits"}) {
        aboutMe
        address
        businessName
        emailAddress
        ownerName
        phoneNumber
        profilePhoto {
          id
          url
          width
          height
        }
      }
      carouselPhotos {
        id
        carouselPhotos {
          height
          url
          width
          id
        }
      }
  }
  `
  
  export async function getStaticProps() {
    const { photographyServices, profile, carouselPhotos } = await hygraph.request(QUERY)
    return {
      props: {
        photographyServices,
        profile,
        carouselPhotos
      }
    }
  }

