import React from "react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Services from './services'
import About from './about'
import NavMenu from '../components/navMenu';
import Contact from './contact'
import VideoDisplay from './videoDisplay';
import Footer from '../components/footer';
import { GraphQLClient } from 'graphql-request';


export default function Home({photographyServices, profiles}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Reed Rogers Portrait's</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavMenu />
      <h1>{profiles.businessName}</h1>
      <Services photographyServices={photographyServices}/>
      <About profiles={profiles}/>
      <VideoDisplay/>
      <Contact profiles={profiles}/>
      <Footer/>
    </div>
  )
}




const hygraph = new GraphQLClient(
    process.env.NEXT_PUBLIC_CLIENT_URL,
    {
      headers: {
        Authorization: `Bearer ${process.env.BEARER_TOKEN}`
      }
    }
  );

  import { gql } from 'graphql-request';


  const QUERY = gql`
  query Services {
    photographyServices {
      id
      serviceTitle
      photoSamples {
        id
      }
    }
    profiles {
      id
      phoneNumber
      ownerName
      profilePhoto {
        id
      }
      businessName
      address
      aboutMe
      emailAddress
    }
  }
  `
  
  export async function getStaticProps() {
    const { photographyServices, profiles } = await hygraph.request(QUERY)
    // console.log(photographyServices)
    // console.log(profiles)
    return {
      props: {
        photographyServices,
        profiles
      }
    }
  }

